### ISSUE TITLE
Cannot use the latest version v2.5.x with nodejs

### ISSUE THREAD

**Issue by datencia** [lhncbc/ucum-lhc#9]
Hi, first thank you for this library.

I'm trying to use it in a new empty node project from scratch, but I'm getting the next error `Error: Cannot find module 'is-integer'`

After installing it manually I've got the next one `Error: Cannot find module '../data/ucumDefs.json'`

Looking at the `node_modules/@lhncbc/ucum-lhc` folder seems the `is-integer` package is not declared as a dependency in the `package.json` file and the `data` folder is missing

**Comment by lmericle** [comment]
Thanks so much for letting us know about this problem.  I suspect that I published an older version of the library - SORRY.  I've updated it and it looks good.  Please try it again.  I think everything should be there now.  Please let me know, at your convenience, and thanks again for contacting us.

**Comment by datencia** [comment]
Great! Thanks a lot. Now it's working using v2.5.4: :fireworks:
